'use client';

import { motion } from 'framer-motion';
import { X, Trophy, Target, Zap, Brain, Download, Share2, BarChart3, CheckCircle2, XCircle, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/Button';
import { Submission } from '@/lib/types';
import { useMockStore } from '@/store/useMockStore';
import { SEED_ASSESSMENTS } from '@/lib/mockQuestions';
import { toast } from 'sonner';

interface Props {
  submission: Submission;
  onClose: () => void;
}

export function AssessmentResults({ submission, onClose }: Props) {
  const { assessments } = useMockStore();
  const assessment = assessments.find(a => a.id === submission.assessmentId) || SEED_ASSESSMENTS.find(a => a.id === submission.assessmentId);

  const feedback = submission.aiFeedback as any;
  const accuracy = submission.accuracy;
  const timeMins = Math.round(submission.timeSpentSeconds / 60);
  const hiringProbability = Math.min(95, Math.max(5, Math.round(accuracy * 0.85 + (submission.telemetry.antiCheatWarnings === 0 ? 10 : 0))));

  const handleShare = async () => {
    const text = `🏆 PlacePrep Mock Hub Result\n📋 ${assessment?.title || 'Assessment'}\n📊 Score: ${submission.score}/${submission.maxScore} (${accuracy.toFixed(0)}%)\n⏱️ Time: ${timeMins}m\n🎯 Hiring Probability: ${hiringProbability}%`;

    if (navigator.share) {
      try {
        await navigator.share({ title: 'PlacePrep Assessment Result', text });
        toast.success('Shared successfully!');
      } catch {
        // User cancelled or not supported, fallback
        await navigator.clipboard.writeText(text);
        toast.success('Result copied to clipboard!');
      }
    } else {
      await navigator.clipboard.writeText(text);
      toast.success('Result copied to clipboard!');
    }
  };

  const handlePDF = () => {
    // Generate printable view
    const printContent = `
      <html><head><title>${assessment?.title} - Results</title>
      <style>body{font-family:system-ui;padding:40px;max-width:800px;margin:auto}
      h1{font-size:24px;margin-bottom:8px}h2{font-size:18px;color:#666;margin-top:32px}
      .stat{display:inline-block;margin-right:32px;margin-bottom:16px}.stat-label{font-size:12px;color:#999;text-transform:uppercase}
      .stat-value{font-size:28px;font-weight:bold}.section{margin:16px 0;padding:16px;background:#f9f9f9;border-radius:8px}
      ul{padding-left:20px}li{margin:8px 0}</style></head><body>
      <h1>${assessment?.title || 'Assessment'} — Performance Report</h1>
      <p>Date: ${new Date(submission.completedAt).toLocaleDateString()}</p>
      <div><div class="stat"><div class="stat-label">Score</div><div class="stat-value">${submission.score}/${submission.maxScore}</div></div>
      <div class="stat"><div class="stat-label">Accuracy</div><div class="stat-value">${accuracy.toFixed(0)}%</div></div>
      <div class="stat"><div class="stat-label">Time</div><div class="stat-value">${timeMins}m</div></div>
      <div class="stat"><div class="stat-label">Hiring Probability</div><div class="stat-value">${hiringProbability}%</div></div></div>
      ${feedback ? `
      <h2>AI Analysis</h2><div class="section"><p>${feedback.summary || ''}</p></div>
      <h2>Strengths</h2><ul>${(feedback.strengths || []).map((s: string) => `<li>${s}</li>`).join('')}</ul>
      <h2>Areas for Improvement</h2><ul>${(feedback.weaknesses || []).map((w: string) => `<li>${w}</li>`).join('')}</ul>
      ` : ''}
      <p style="margin-top:40px;color:#aaa;font-size:12px">Generated by PlacePrep Mock Hub</p></body></html>`;

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(printContent);
      printWindow.document.close();
      printWindow.print();
    }
    toast.success('PDF dialog opened!');
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 bg-background/80 backdrop-blur-2xl z-[150] flex items-center justify-center p-4"
    >
      <motion.div
        initial={{ scale: 0.9, y: 40 }}
        animate={{ scale: 1, y: 0 }}
        transition={{ type: 'spring', stiffness: 200, damping: 25 }}
        className="bg-card/80 backdrop-blur-3xl border border-white/10 rounded-[48px] w-full max-w-4xl max-h-[90vh] overflow-y-auto custom-scrollbar shadow-2xl"
      >
        {/* Header */}
        <div className="relative p-10 md:p-14 border-b border-white/5">
          <button onClick={onClose} className="absolute top-6 right-6 md:top-10 md:right-10 p-3 rounded-full hover:bg-white/10 text-muted-foreground hover:text-white transition-all" aria-label="Close results">
            <X className="w-5 h-5" />
          </button>

          <div className="space-y-4">
            <div className="flex items-center gap-3 flex-wrap">
              <span className="px-4 py-2 rounded-2xl bg-primary/10 border border-primary/20 text-[10px] font-black text-primary uppercase tracking-widest">
                {assessment?.companyTags?.[0] || assessment?.category || 'Assessment'}
              </span>
              {submission.telemetry.antiCheatWarnings > 0 && (
                <span className="px-4 py-2 rounded-2xl bg-amber-500/10 border border-amber-500/20 text-[10px] font-black text-amber-500 uppercase tracking-widest flex items-center gap-2">
                  <AlertTriangle className="w-3 h-3" /> {submission.telemetry.antiCheatWarnings} integrity warnings
                </span>
              )}
            </div>
            <h2 className="text-3xl md:text-5xl font-black text-foreground tracking-tight">{assessment?.title || 'Assessment'}</h2>
            <p className="text-sm font-medium text-muted-foreground">{new Date(submission.completedAt).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}</p>
          </div>
        </div>

        {/* Scores */}
        <div className="p-10 md:p-14 grid grid-cols-2 md:grid-cols-4 gap-6 border-b border-white/5">
          <div className="text-center p-6 rounded-[32px] bg-white/5 border border-white/10">
            <div className={`text-4xl md:text-5xl font-black tabular-nums ${accuracy >= 80 ? 'text-emerald-500' : accuracy >= 60 ? 'text-primary' : 'text-rose-500'}`}>
              {accuracy.toFixed(0)}%
            </div>
            <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground mt-2">Accuracy</p>
          </div>
          <div className="text-center p-6 rounded-[32px] bg-white/5 border border-white/10">
            <div className="text-4xl md:text-5xl font-black tabular-nums text-foreground">{submission.score}/{submission.maxScore}</div>
            <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground mt-2">Score</p>
          </div>
          <div className="text-center p-6 rounded-[32px] bg-white/5 border border-white/10">
            <div className="text-4xl md:text-5xl font-black tabular-nums text-foreground">{timeMins}m</div>
            <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground mt-2">Time Spent</p>
          </div>
          <div className="text-center p-6 rounded-[32px] bg-gradient-to-br from-primary/10 to-indigo-500/10 border border-primary/20">
            <div className="text-4xl md:text-5xl font-black tabular-nums text-primary">{hiringProbability}%</div>
            <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground mt-2">Hiring Probability</p>
          </div>
        </div>

        {/* AI Feedback */}
        {feedback && (
          <div className="p-10 md:p-14 space-y-8 border-b border-white/5">
            <div className="flex items-center gap-3">
              <Brain className="w-5 h-5 text-primary" />
              <h3 className="text-sm font-black uppercase tracking-[0.3em] text-foreground">AI Analysis</h3>
            </div>

            <p className="text-base font-medium text-muted-foreground leading-relaxed">{feedback.summary}</p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="p-6 rounded-[28px] bg-emerald-500/5 border border-emerald-500/10 space-y-4">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                  <span className="text-[10px] font-black uppercase tracking-widest text-emerald-500">Strengths</span>
                </div>
                <ul className="space-y-3">
                  {(feedback.strengths || []).map((s: string, i: number) => (
                    <li key={i} className="text-sm font-medium text-muted-foreground flex items-start gap-3">
                      <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 mt-1.5 shrink-0" />
                      {s}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="p-6 rounded-[28px] bg-rose-500/5 border border-rose-500/10 space-y-4">
                <div className="flex items-center gap-2">
                  <XCircle className="w-4 h-4 text-rose-500" />
                  <span className="text-[10px] font-black uppercase tracking-widest text-rose-500">Weaknesses</span>
                </div>
                <ul className="space-y-3">
                  {(feedback.weaknesses || []).map((w: string, i: number) => (
                    <li key={i} className="text-sm font-medium text-muted-foreground flex items-start gap-3">
                      <div className="w-1.5 h-1.5 rounded-full bg-rose-500 mt-1.5 shrink-0" />
                      {w}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        )}

        {/* Telemetry */}
        <div className="p-10 md:p-14 space-y-6 border-b border-white/5">
          <div className="flex items-center gap-3">
            <BarChart3 className="w-5 h-5 text-primary" />
            <h3 className="text-sm font-black uppercase tracking-[0.3em] text-foreground">Telemetry</h3>
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="p-4 rounded-2xl bg-white/5 border border-white/10">
              <span className="text-xl font-black text-foreground tabular-nums">{submission.telemetry.speed.toFixed(1)}</span>
              <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground mt-1">Qs/min</p>
            </div>
            <div className="p-4 rounded-2xl bg-white/5 border border-white/10">
              <span className="text-xl font-black text-foreground tabular-nums">{submission.telemetry.hesitationPoints}</span>
              <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground mt-1">Flagged</p>
            </div>
            <div className="p-4 rounded-2xl bg-white/5 border border-white/10">
              <span className="text-xl font-black text-foreground tabular-nums">{submission.telemetry.antiCheatWarnings}</span>
              <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground mt-1">Tab Switches</p>
            </div>
            <div className="p-4 rounded-2xl bg-white/5 border border-white/10">
              <span className="text-xl font-black text-foreground tabular-nums">{assessment?.totalQuestions || '—'}</span>
              <p className="text-[9px] font-black uppercase tracking-widest text-muted-foreground mt-1">Total Questions</p>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="p-10 md:p-14 flex items-center justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-4 flex-wrap">
            <Button onClick={handleShare} variant="secondary" className="flex items-center gap-2">
              <Share2 className="w-4 h-4" /> Share Result
            </Button>
            <Button onClick={handlePDF} variant="secondary" className="flex items-center gap-2">
              <Download className="w-4 h-4" /> PDF Report
            </Button>
          </div>
          <Button onClick={onClose} variant="primary">Close & Continue</Button>
        </div>
      </motion.div>
    </motion.div>
  );
}
